### ISSUE TITLE
Consulta acerca de GitHub y Copilot

### ISSUE THREAD

**Issue by AldanaCarnero** [inkua/Principal#25]
Hola! Recién hoy pude ponerme las pilas con Github, vi el tutorial que dictó @frankinkua del área de sistemas unos días atrás, creé mi perfil y actualicé algunos datos... Pero me surgió una duda que no quería quedarme sin plantear: Hacia el final de la presentación Frank nos habló sobre Copilot y la inteligencia artificial, sus ventajas y demás. No me quedó claro cómo podemos utilizarlo, es decir si debemos instalar y saber manejar tanto Copilot como GitHub Desktop y Visual Studio Code, y en caso de que así sea, si son muy complejos de manejar para quienes no estamos tan metidos en el rubro IT como es mi caso. Gracias de antemano por su respuesta a quien pueda sacarme la duda!

**Comment by frankinkua** [comment]
Hola Aldana! cómo estas?
Si hay que instalar esas 3 herramientas, más la extensión de Visual Studio Code para utilizar copilot. Creo que cualquiera puede aprender a usarlas!
