### ISSUE TITLE
Consulta

### ISSUE THREAD

**Issue by Ornellamc** [inkua/Principal#26]
Hola, buenas tardes! Estuve poniéndome al día con GitHub y tratando de entenderlo aún mejor. Una de las ideas principales para los usuarios es que vayamos sumando los proyectos o ideas de cada área dentro de sus respectivas carpetas, por ejemplo?

**Comment by frankinkua** [comment]
Hola @Ornellamc! perdón por la demora. Si, pero estamos trabajando en el formato y vamos a armar una clase explicar bien!

**Comment by Ornellamc** [comment]
Perfecto Frank, no hay problema. Muchas gracias!
